// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpgsjbwwbfjedvkmlvxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwZ3NqYnd3YmZqZWR2a21sdnh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5Mjk2MzcsImV4cCI6MjA3NTUwNTYzN30.TtEnqMC-BmWqxZU2zq_C1zgyQefE3FHUZvHuZAOogtU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});